=== sevenmachines/cryomesh/TestData/SequenceChannels.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT PatternChannels (PatternChannel+)>
<!ATTLIST PatternChannels
	Version CDATA #REQUIRED   
	Description CDATA #IMPLIED> 

<!ELEMENT PatternChannel (Pattern+)>
<!ATTLIST PatternChannel
    ReferenceID CDATA #REQUIRED 
	Type CDATA #REQUIRED 
	Depth CDATA #REQUIRED
	Width CDATA #REQUIRED
    Note CDATA #IMPLIED>
      
<!ELEMENT Pattern EMPTY>
<!ATTLIST Pattern
	Tag CDATA	#REQUIRED 
	Binary CDATA #REQUIRED>

=== sevenmachines/cryomesh/TestData/sequences_3x2x3.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE PatternChannels SYSTEM "SequenceChannels.dtd" >

<PatternChannels Description="Randomly generated set of sequences (3x2x3)" Version="0.1">

	<PatternChannel Note="Randomly generated Input" Type="Input" ReferenceID="1" Width="3" Depth="2">
		<Pattern Binary="011" Tag="" />
		<Pattern Binary="101" Tag="" />
	</PatternChannel>

	<PatternChannel Note="Randomly generated Input" Type="Input" ReferenceID="2" Width="3" Depth="2">
		<Pattern Binary="010" Tag="" />
		<Pattern Binary="010" Tag="" />
	</PatternChannel>

	<PatternChannel Note="Randomly generated Input" Type="Input" ReferenceID="3" Width="3" Depth="2">
		<Pattern Binary="000" Tag="" />
		<Pattern Binary="100" Tag="" />
	</PatternChannel>

	<PatternChannel Note="Randomly generated Output" Type="Output" ReferenceID="1001" Width="3" Depth="2">
		<Pattern Binary="101" Tag="" />
		<Pattern Binary="001" Tag="" />
	</PatternChannel>

	<PatternChannel Note="Randomly generated Output" Type="Output" ReferenceID="1002" Width="3" Depth="2">
		<Pattern Binary="101" Tag="" />
		<Pattern Binary="111" Tag="" />
	</PatternChannel>

	<PatternChannel Note="Randomly generated Output" Type="Output" ReferenceID="1003" Width="3" Depth="2">
		<Pattern Binary="011" Tag="" />
		<Pattern Binary="111" Tag="" />
	</PatternChannel>

</PatternChannels>
